package com.project.artisancharcuterie.domain;

import com.project.artisancharcuterie.domain.enums.BatchStatus;
import com.project.artisancharcuterie.domain.enums.ProductType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Core aggregate root, represents a single cured-meat production batch.
 * Tracks provenance (farm, breed), initial weight, salt-cure timeline,
 * current lifecycle status, and current chamber placement.
 */
@Entity
@Table(name = "batches", uniqueConstraints = @UniqueConstraint(columnNames = "batch_code"))
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Batch {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable business key, e.g. "PRO-2026-001".
     * Generated by the service layer; unique across the system.
     */
    @Column(name = "batch_code", nullable = false, length = 30)
    private String batchCode;

    @ManyToOne(fetch = FetchType.EAGER, optional = false)
    @JoinColumn(name = "farm_id", nullable = false)
    private Farm farm;

    @Enumerated(EnumType.STRING)
    @Column(name = "product_type", nullable = false, length = 20)
    private ProductType productType;

    /** Specific breed of animal for this batch. May differ from farm's primary breed. */
    @Column(name = "animal_breed", nullable = false, length = 100)
    private String animalBreed;

    /** Initial weight at intake, in kilograms. */
    @Column(name = "initial_weight_kg", nullable = false, precision = 10, scale = 3)
    private BigDecimal initialWeightKg;

    /** Date the salt cure was applied. Marks the start of the curing clock. */
    @Column(name = "salt_cure_start_date", nullable = false)
    private LocalDate saltCureStartDate;

    /**
     * target total aging duration in months.
     * Defaults to the product type's standard but may be overridden by the artisan.
     */
    @Column(name = "target_aging_months", nullable = false)
    private Integer targetAgingMonths;

    @Enumerated(EnumType.STRING)
    @Column(name = "current_status", nullable = false, length = 20)
    @Builder.Default
    private BatchStatus currentStatus = BatchStatus.GREEN;

    /**
     * The chamber this batch is currently housed in.
     * Null when RETAIL_READY (batch has left the aging environment).
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "current_chamber_id")
    private Chamber currentChamber;

    @Column(length = 500)
    private String notes;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

}
